### ISSUE TITLE
CAS simplification doesn't understand that root(x^n, n)=x

### ISSUE THREAD

**Issue by eklipse2009** [Omega-Numworks/Omega#431]
#### Describe the bug
![image](https://user-images.githubusercontent.com/4990107/101592944-c7fec500-39f7-11eb-9810-e1077efa5929.png)

#### Environment
 - Omega Version: 1.20.3

**Comment by M4xi1m3** [comment]
Actually it does...
For cases where it is true and where it is absolutely sure it is. This is not true for all numbers. As an example, root((-1)^2, 2) = 1. If you try root(abs(x)^n),n), it will simplify it as abs(x).

**Comment by eklipse2009** [comment]
@M4xi1m3 you're right about root(abs(x)^n), n). But I still think you're too quick to dismiss this bug, because root(x^3, 3)=x. This is valid for all cases where n is odd. But when n is even, root(x^2, 2)=abs(x), Omega doesn't handle it right.
Besides, many other CAS implementations don't have any problems simplifying both root(x^2, 2) and root(x^3, 3) correctly, e. g. HP Prime.

![image](https://user-images.githubusercontent.com/4990107/101676228-902d6700-3a63-11eb-88cb-6f213a2a4e2d.png)

![image](https://user-images.githubusercontent.com/4990107/101676175-80ae1e00-3a63-11eb-9bd2-ba747a9d8890.png)

**Comment by quentinguidee** [comment]
Hi @eklipse2009 ! Thank you for this issue.

However, the issue you're pointing out should also appears Upstream (aka. on Epsilon). With Omega, we don't fix issues caused by Upstream. In facts, if this issue is solved in Omega and then in Epsilon, it will cause conflicts while merging upstream.

Even if these CAS features are not available on Epsilon for the moment, they're still in their code (just disabled for the moment).

**Comment by quentinguidee** [comment]
In investigation (see https://github.com/numworks/epsilon/issues/1729)

**Comment by quentinguidee** [comment]
Numworks doesn't want to fix it in Epsilon, so we did it and it should be fixed in Omega 1.21.0 (should be released soon).
This issue will be closed when #435 will be merged.

**Comment by eklipse2009** [comment]
Thank you, guys, you're awesome!

**Comment by ladyeklipse** [comment]
As of March 11, 2021, in Omega 1.21.0 Epsilon 15.3.1, this bug still can be reproduced.
